# Generated by Django 2.0.2 on 2018-04-16 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0003_vehicle_vtype'),
        ('tolls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('eTollTxnID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gatewayTxnID', models.CharField(max_length=100, unique=True)),
                ('ttype', models.CharField(max_length=10)),
                ('dl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('eTollID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tolls.eToll')),
                ('rc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
        ),
    ]
