# Generated by Django 2.0.2 on 2018-04-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolls', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='usability',
            field=models.IntegerField(default=0),
        ),
    ]
