# Generated by Django 2.0.2 on 2018-04-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolls', '0004_auto_20180416_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='modified_date',
            field=models.DateTimeField(),
        ),
    ]
