# Generated by Django 2.0.2 on 2018-04-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolls', '0005_auto_20180417_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='modified_date',
            field=models.DateTimeField(null=True),
        ),
    ]
