# Generated by Django 2.0.2 on 2018-04-17 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tolls', '0006_auto_20180417_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='created_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='modified_date',
            new_name='modified',
        ),
    ]
