# Generated by Django 2.0.2 on 2018-04-17 21:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tolls', '0007_auto_20180417_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='id',
            field=models.AutoField(auto_created=True, default='-1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='eTollTxnID',
            field=models.CharField(max_length=100),
        ),
    ]
