# Generated by Django 2.0.2 on 2018-04-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolls', '0008_auto_20180417_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='validity',
            field=models.BooleanField(default=True),
        ),
    ]
