# Generated by Django 2.0.2 on 2018-04-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolls', '0009_transaction_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_paid',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
