# Generated by Django 2.0.2 on 2018-04-16 05:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=datetime.datetime(2018, 4, 16, 5, 1, 25, 478561, tzinfo=utc), max_length=300),
            preserve_default=False,
        ),
    ]
