# Generated by Django 2.0.2 on 2018-04-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20180416_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vtype',
            field=models.CharField(default='', max_length=10),
        ),
    ]
