# Generated by Django 2.0.2 on 2018-04-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20180418_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vmodel',
            field=models.CharField(default='', max_length=300),
        ),
    ]
