# Generated by Django 2.0.2 on 2018-04-21 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_vehicle_vname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='sharedWith',
            field=models.ManyToManyField(default=None, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
